// Code generated by protoc-gen-gogo.
// source: bulk_chunk_request.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	bulk_chunk_request.proto
	bulk_chunk_response.proto
	chunk_request.proto
	chunk_response.proto
	internal_message.proto
	node_meta.proto
	player.proto
	player_action.proto

It has these top-level messages:
	BulkChunkRequest
*/
package protobuf

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type BulkChunkRequest struct {
	ChunksX          []int64 `protobuf:"varint,1,rep,name=chunks_x" json:"chunks_x,omitempty"`
	ChunksY          []int64 `protobuf:"varint,2,rep,name=chunks_y" json:"chunks_y,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BulkChunkRequest) Reset()         { *m = BulkChunkRequest{} }
func (m *BulkChunkRequest) String() string { return proto.CompactTextString(m) }
func (*BulkChunkRequest) ProtoMessage()    {}

func (m *BulkChunkRequest) GetChunksX() []int64 {
	if m != nil {
		return m.ChunksX
	}
	return nil
}

func (m *BulkChunkRequest) GetChunksY() []int64 {
	if m != nil {
		return m.ChunksY
	}
	return nil
}

func init() {
}
