// Code generated by protoc-gen-gogo.
// source: chat_message.proto
// DO NOT EDIT!

package protobuf

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// discarding unused import gogoproto "code.google.com/p/gogoprotobuf/gogoproto/gogo.pb"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ChatMessage struct {
	Message          string `protobuf:"bytes,1,req,name=message" json:"message"`
	Uuid             string `protobuf:"bytes,3,req,name=uuid" json:"uuid"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}

func (m *ChatMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChatMessage) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
}
