// Code generated by protoc-gen-gogo.
// source: chunk_response.proto
// DO NOT EDIT!

package protobuf

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// discarding unused import gogoproto "code.google.com/p/gogoprotobuf/gogoproto/gogo.pb"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ChunkResponse struct {
	X                int64  `protobuf:"varint,1,req,name=x" json:"x"`
	Z                int64  `protobuf:"varint,2,req,name=z" json:"z"`
	Data             []byte `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	Uuid             string `protobuf:"bytes,4,opt,name=uuid" json:"uuid"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ChunkResponse) Reset()         { *m = ChunkResponse{} }
func (m *ChunkResponse) String() string { return proto.CompactTextString(m) }
func (*ChunkResponse) ProtoMessage()    {}

func (m *ChunkResponse) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ChunkResponse) GetZ() int64 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *ChunkResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ChunkResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
}
