// Code generated by protoc-gen-gogo.
// source: protobuf/internal_message.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	protobuf/internal_message.proto
	protobuf/node_meta.proto

It has these top-level messages:
	InternalMessage
	ChunkRequest
*/
package protobuf

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type InternalMessage struct {
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *InternalMessage) Reset()         { *m = InternalMessage{} }
func (m *InternalMessage) String() string { return proto.CompactTextString(m) }
func (*InternalMessage) ProtoMessage()    {}

var extRange_InternalMessage = []proto.ExtensionRange{
	{100, 199},
}

func (*InternalMessage) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_InternalMessage
}
func (m *InternalMessage) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

type ChunkRequest struct {
	X                *int64 `protobuf:"varint,1,req,name=x" json:"x,omitempty"`
	Y                *int64 `protobuf:"varint,2,req,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ChunkRequest) Reset()         { *m = ChunkRequest{} }
func (m *ChunkRequest) String() string { return proto.CompactTextString(m) }
func (*ChunkRequest) ProtoMessage()    {}

func (m *ChunkRequest) GetX() int64 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *ChunkRequest) GetY() int64 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

var E_ChunkRequest = &proto.ExtensionDesc{
	ExtendedType:  (*InternalMessage)(nil),
	ExtensionType: (*ChunkRequest)(nil),
	Field:         100,
	Name:          "protobuf.chunk_request",
	Tag:           "bytes,100,opt,name=chunk_request",
}

func init() {
	proto.RegisterExtension(E_ChunkRequest)
}
