// Code generated by protoc-gen-gogo.
// source: node_meta.proto
// DO NOT EDIT!

package protobuf

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// discarding unused import gogoproto "code.google.com/p/gogoprotobuf/gogoproto/gogo.pb"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type NodeMeta struct {
	Addr             string `protobuf:"bytes,1,req,name=addr" json:"addr"`
	Type             string `protobuf:"bytes,2,req,name=type" json:"type"`
	X                *int64 `protobuf:"varint,3,opt,name=x" json:"x,omitempty"`
	Z                *int64 `protobuf:"varint,4,opt,name=z" json:"z,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NodeMeta) Reset()         { *m = NodeMeta{} }
func (m *NodeMeta) String() string { return proto.CompactTextString(m) }
func (*NodeMeta) ProtoMessage()    {}

func (m *NodeMeta) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *NodeMeta) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NodeMeta) GetX() int64 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *NodeMeta) GetZ() int64 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

func init() {
}
