// Code generated by protoc-gen-gogo.
// source: subscription.proto
// DO NOT EDIT!

package protobuf

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// discarding unused import gogoproto "code.google.com/p/gogoprotobuf/gogoproto/gogo.pb"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Subscription struct {
	Subscribe        bool   `protobuf:"varint,1,req,name=subscribe" json:"subscribe"`
	Uuid             string `protobuf:"bytes,2,opt,name=uuid" json:"uuid"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}

func (m *Subscription) GetSubscribe() bool {
	if m != nil {
		return m.Subscribe
	}
	return false
}

func (m *Subscription) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
}
