// Code generated by protoc-gen-gogo.
// source: subscribe.proto
// DO NOT EDIT!

package protobuf

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// discarding unused import gogoproto "code.google.com/p/gogoprotobuf/gogoproto/gogo.pb"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Subscribe struct {
	Uuid             string `protobuf:"bytes,1,opt,name=uuid" json:"uuid"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Subscribe) Reset()         { *m = Subscribe{} }
func (m *Subscribe) String() string { return proto.CompactTextString(m) }
func (*Subscribe) ProtoMessage()    {}

func (m *Subscribe) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
}
